input_dir: ../
output_dir: Generated

strings:
  inputs: [Localization/en.lproj/Localizable.strings, Localization/NotLocalizable.strings]
  outputs:
    templatePath: Templates/custom-strings-template-swift4.stencil
    output: Strings.swift
    
ib:
  inputs: [Storyboards]
  outputs:
    - templateName: scenes-swift4
      output: Storyboard Scenes.swift
    - templateName: segues-swift4
      output: Storyboard Segues.swift
      
xcassets:
  inputs:
    - Images.xcassets
    - Colors.xcassets
  outputs:
    - templateName: swift4
      output: Assets.swift

fonts:
  inputs: Fonts
  outputs:
    templateName: swift4
    output: Fonts.swift
